package NETWORKING;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASIF
 */
public class ClientClass extends javax.swing.JFrame {
static Socket s;
    /**
     * Creates new form ClientClass
     */
    public ClientClass() throws UnknownHostException, IOException {
        initComponents();           
        setVisible(true);
        txtrec.setWrapStyleWord(true);
        setBounds(630, 5, 410, 310);
        getContentPane().setBackground(new java.awt.Color(51, 51, 0));
        String st="";
        String host="ASIF-PC";
        InetAddress ad=InetAddress.getByName(host);
         s=new Socket(ad,8888);
         lblstatus.setText("Connected To Server");
         while(true){
                        DataInputStream dis = new DataInputStream(s.getInputStream());
                        String str=dis.readUTF();
                        txtrec.setText(st.concat(str));
                        st=st+str+"\n";                        
         }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtrec = new javax.swing.JTextArea();
        txtarea = new javax.swing.JTextField();
        lblstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setBackground(new java.awt.Color(51, 51, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtrec.setBackground(new java.awt.Color(204, 255, 255));
        txtrec.setColumns(20);
        txtrec.setEditable(false);
        txtrec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtrec.setRows(5);
        txtrec.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtrec);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 346, 190));

        txtarea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareaActionPerformed(evt);
            }
        });
        txtarea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtareaFocusGained(evt);
            }
        });
        getContentPane().add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 345, 30));

        lblstatus.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(0, 255, 255));
        lblstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstatus.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 345, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareaActionPerformed
        // TODO add your handling code here:
        try {
            DataOutputStream dos = new DataOutputStream(s.getOutputStream());
            dos.writeUTF(txtarea.getText());
        } catch (IOException ex) {
            Logger.getLogger(ClientClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtarea.setText("");
    }//GEN-LAST:event_txtareaActionPerformed

    private void txtareaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtareaFocusGained
        // TODO add your handling code here:
        lblstatus.setVisible(false);
        lblstatus.updateUI();
    }//GEN-LAST:event_txtareaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnknownHostException, IOException {
        new ClientClass().setVisible(true);
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel lblstatus;
    private javax.swing.JTextField txtarea;
    private static javax.swing.JTextArea txtrec;
    // End of variables declaration//GEN-END:variables
}
