/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NETWORKING;

import java.awt.*;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author ASIF
 */
import java.io.*;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
public class ServerClass extends javax.swing.JFrame {
static Socket s;
    /**
     * Creates new form ServerClass
     */
    public ServerClass() throws IOException {
        initComponents(); 
        setVisible(true);
        txtrec.setWrapStyleWord(true);
        setBounds(200, 5, 410, 310);
        getContentPane().setBackground(new java.awt.Color(51, 51, 0));
        ServerSocket ss=new ServerSocket(8888);
        String st="";
        s=ss.accept();
        lblstatus.setText("Connection Estabished!");
        while(true){
            DataInputStream dis=new DataInputStream(s.getInputStream());
            String str=dis.readUTF();    
            txtrec.setText(st.concat(str));
            st=st+str+"\n";                      
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtrec = new javax.swing.JTextArea();
        lblstatus = new javax.swing.JLabel();
        txtarea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setBackground(new java.awt.Color(51, 51, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtrec.setBackground(new java.awt.Color(204, 255, 255));
        txtrec.setColumns(20);
        txtrec.setEditable(false);
        txtrec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtrec.setRows(5);
        txtrec.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtrec);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 346, 191));

        lblstatus.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(0, 255, 255));
        lblstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstatus.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblstatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblstatusFocusLost(evt);
            }
        });
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 346, 26));

        txtarea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareaActionPerformed(evt);
            }
        });
        txtarea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtareaFocusGained(evt);
            }
        });
        getContentPane().add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 346, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblstatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblstatusFocusLost
        // TODO add your handling code here:        
    }//GEN-LAST:event_lblstatusFocusLost

    private void txtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareaActionPerformed
        // TODO add your handling code here:
        try {
            DataOutputStream dos = new DataOutputStream(s.getOutputStream());
            dos.writeUTF(txtarea.getText());
        } catch (IOException ex) {
            Logger.getLogger(ServerClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtarea.setText("");
    }//GEN-LAST:event_txtareaActionPerformed

    private void txtareaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtareaFocusGained
        // TODO add your handling code here:
        lblstatus.setVisible(false);
        lblstatus.updateUI();
    }//GEN-LAST:event_txtareaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
//        Thread t=Thread.currentThread();
//        System.out.println("Current Thread: "+t);
//        System.out.println("Its Name: "+t.getName());
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                try {
                     //initComponents();
                    new ServerClass();
//                } catch (IOException ex) {
//                    Logger.getLogger(ServerClass.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
                
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel lblstatus;
    private javax.swing.JTextField txtarea;
    public static javax.swing.JTextArea txtrec;
    // End of variables declaration//GEN-END:variables
}
